package org.pickaid.pibrary.api.facet;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a chunk-scoped facet whose descriptor is generated by PiSerializeKit.
 */
@Retention(RetentionPolicy.SOURCE)
@Target(ElementType.TYPE)
public @interface PiChunkFacet {
    String namespace();

    String path();
}
