@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package org.crychicteam.cibrary.fastprojectileapi.collision;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;